name: Get Weekly List of Malicious Pages

on:
  schedule:
    - cron: '0 0 * * 0'
  push:
    branches:
      - main

env:
    IMAGE_NAME: kacpermalachowski/hazard-halt/prod
    DOCKERFILE: Dockerfile
    CAPROVER_APP: hazard-halt-dc-bot
    DOCKER_REGISTRY: ghcr.io

jobs:
  get-malicious-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Current Malicious Pages
        run: curl https://hole.cert.pl/domains/domains.json | jq 'map(select(.DeleteDate == null))' > ./domains.json
      - run: |
          echo "IMAGE_NAME_WITH_REGISTRY=$DOCKER_REGISTRY/$IMAGE_NAME" >> $GITHUB_ENV
          export IMAGE_NAME_WITH_REGISTRY=$DOCKER_REGISTRY/$IMAGE_NAME
          echo "FULL_IMAGE_NAME=$IMAGE_NAME_WITH_REGISTRY:$GITHUB_SHA" >> $GITHUB_ENV
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: |
            ghcr.io/${{ github.repository }}/malicious-pages-bot:latest
            ghcr.io/${{ github.repository }}/malicious-pages-bot:$("${{ github.sha }}".SubString(0, 8))
          push: true

      - name: Deploy to CapRover
        uses: caprover/deploy-from-github@d76580d79952f6841c453bb3ed37ef452b19752c
        with:
          server: ${{ secrets.CAPROVER_HOST }}
          app: ${{ env.CAPROVER_APP }}
          token: ${{ secrets.CAPROVER_TOKEN }}
          image: ${{ env.FULL_IMAGE_NAME }}
